{{- if .Profile.Multirail -}}
{{- /* Create separate SriovNetworkNodePolicy per PF using rootDevices */ -}}
{{- range $i, $pf := .ClusterConfig.PFs}}
{{- if eq $pf.Traffic "east-west"}}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: infiniband-sriov-{{printf "%c" (add 97 $i)}}
  namespace: {{$.NetworkOperator.Namespace}}
spec:
  deviceType: netdevice
  mtu: {{$.Sriov.Mtu}}
  {{- if $.ClusterConfig.NodeSelector }}
  nodeSelector:
    {{- range $key, $value := $.ClusterConfig.NodeSelector }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
  nicSelector:
    vendor: "15b3"
    rootDevices:
      - "{{$pf.PciAddress}}"
  linkType: IB
  isRdma: true
  numVfs: {{$.Sriov.NumVfs}}
  priority: {{$.Sriov.Priority}}
  resourceName: {{$.Sriov.ResourceName}}-{{printf "%c" (add 97 $i)}}
{{if ne $i (sub (len $.ClusterConfig.PFs) 1)}}---{{end -}}
{{- end -}}
{{- end -}}
{{- else -}}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: infiniband-sriov
  namespace: {{.NetworkOperator.Namespace}}
spec:
  deviceType: netdevice
  mtu: {{.Sriov.Mtu}}
  {{- if $.ClusterConfig.NodeSelector }}
  nodeSelector:
    {{- range $key, $value := $.ClusterConfig.NodeSelector }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
  nicSelector:
    vendor: "15b3"
  linkType: IB
  isRdma: true
  numVfs: {{.Sriov.NumVfs}}
  priority: {{.Sriov.Priority}}
  resourceName: {{.Sriov.ResourceName}}
{{- end}}