{{- if .Profile.Multirail -}}
{{- /* Create separate SR-IOV IB networks for each PF interface */ -}}
{{- range $i, $pf := .ClusterConfig.PFs}}
{{- if eq $pf.Traffic "east-west"}}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovIBNetwork
metadata:
  name: {{$.Sriov.NetworkName}}-{{printf "%c" (add 97 $i)}}
  namespace: {{$.NetworkOperator.Namespace}}
spec:
  ipam: |
    {
      "type": "nv-ipam",
      "poolName": "{{$.NvIpam.PoolName}}-{{printf "%c" (add 97 $i)}}"
    }
  resourceName: {{$.Sriov.ResourceName}}-{{printf "%c" (add 97 $i)}}
  linkState: enable
  networkNamespace: default
{{if ne $i (sub (len $.ClusterConfig.PFs) 1)}}---{{end -}}
{{- end -}}
{{- end -}}
{{- else -}}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovIBNetwork
metadata:
  name: {{.Sriov.NetworkName}}
  namespace: {{.NetworkOperator.Namespace}}
spec:
  ipam: |
    {
      "type": "nv-ipam",
      "poolName": "{{.NvIpam.PoolName}}"
    }
  resourceName: {{.Sriov.ResourceName}}
  linkState: enable
  networkNamespace: default
{{- end}}