apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  ofedDriver:
    image: doca-driver
    repository: {{.NetworkOperator.Repository}}
    version: {{.NetworkOperator.ComponentVersion}}
  rdmaSharedDevicePlugin:
    image: k8s-rdma-shared-dev-plugin
    repository: {{.NetworkOperator.Repository}}
    version: {{.NetworkOperator.ComponentVersion}}
    config: |
      {
        "configList": [
        {{- if .Profile.Multirail -}}
        {{/* Create separate RDMA resources for each PF network interface */}}
          
          {{- range $i, $pf := .ClusterConfig.PFs}}
          {{- if eq $pf.Traffic "east-west"}}
          {
            "resourceName": "{{$.RdmaShared.ResourceName}}_{{printf "%c" (add 97 $i)}}",
            "rdmaHcaMax": {{$.RdmaShared.HcaMax}},
            "selectors": {
              "ifNames": ["{{$pf.NetworkInterface}}"]
            }
          }{{if ne $i (sub (len $.ClusterConfig.PFs) 1)}},{{end}}
          {{- end}}
          {{- end}}
          
        {{- else}}
          {{- /* Create single RDMA resource with all interfaces */ -}}
          {
            "resourceName": "{{.RdmaShared.ResourceName}}",
            "rdmaHcaMax": {{.RdmaShared.HcaMax}},
            "selectors": {
              "ifNames": [{{range $i, $pf := .ClusterConfig.PFs}}{{if gt $i 0}}, {{end}}"{{$pf.NetworkInterface}}"{{end}}]
            }
          }
        {{- end}}
        ]
      }
  nvIpam:
    image: nvidia-k8s-ipam
    repository: {{.NetworkOperator.Repository}}
    version: {{.NetworkOperator.ComponentVersion}}
    imagePullSecrets: []
    enableWebhook: false
  secondaryNetwork:
    cniPlugins:
      image: plugins
      repository: {{.NetworkOperator.Repository}}
      version: {{.NetworkOperator.ComponentVersion}}
    multus:
      image: multus-cni
      repository: {{.NetworkOperator.Repository}}
      version: {{.NetworkOperator.ComponentVersion}}
    ipoib:
      image: ipoib-cni
      repository: {{.NetworkOperator.Repository}}
      version: {{.NetworkOperator.ComponentVersion}}