{{- if .Profile.Multirail -}}
{{- /* Create separate IPoIB networks for each PF network interface */ -}}
{{- range $i, $pf := .ClusterConfig.PFs}}
{{- if eq $pf.Traffic "east-west"}}
apiVersion: mellanox.com/v1alpha1
kind: IPoIBNetwork
metadata:
  name: {{$.Ipoib.NetworkName}}-{{printf "%c" (add 97 $i)}}
spec:
  networkNamespace: "default"
  master: "{{$pf.NetworkInterface}}"
  ipam: |
    {
      "type": "nv-ipam",
      "poolName": "{{$.NvIpam.PoolName}}-{{printf "%c" (add 97 $i)}}"
    }  
{{if ne $i (sub (len $.ClusterConfig.PFs) 1)}}---{{end -}}
{{- end}}
{{- end -}}
{{- else -}}
{{/* Create single shared IPoIB network for all devices */}}
apiVersion: mellanox.com/v1alpha1
kind: IPoIBNetwork
metadata:
  name: {{.Ipoib.NetworkName}}
spec:
  networkNamespace: "default"
  master: "{{(index .ClusterConfig.PFs 0).NetworkInterface}}"
  ipam: |
    {
      "type": "nv-ipam",
      "poolName": "{{.NvIpam.PoolName}}"
    }
{{end}}