apiVersion: v1
kind: Pod
metadata:
  name: hostdev-test-pod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: {{.Hostdev.NetworkName}}
spec:
  {{- if .ClusterConfig.NodeSelector }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          {{- range $key, $value := .ClusterConfig.NodeSelector }}
          - key: {{ $key }}
            {{- if ne $value "" }}
            operator: In
            values:
            - {{ $value }}
            {{- else }}
            operator: Exists
            {{- end }}
          {{- end }}
  {{- end }}
  containers:
  - name: test-container
    image: mellanox/rping-test
    command: ["/bin/bash", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        add: ["IPC_LOCK"]
    resources:
      requests:
        nvidia.com/{{.Hostdev.ResourceName}}: '1'
      limits:
        nvidia.com/{{.Hostdev.ResourceName}}: '1'