{{- if .Profile.Multirail -}}
{{- /* Create test pods for each separate SR-IOV Ethernet network (per PF) */ -}}
{{- range $i, $pf := .ClusterConfig.PFs}}
{{- if eq $pf.Traffic "east-west"}}
apiVersion: v1
kind: Pod
metadata:
  name: sriov-test-pod-{{printf "%c" (add 97 $i)}}
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: {{$.Sriov.NetworkName}}-{{printf "%c" (add 97 $i)}}
spec:
  {{- if $.ClusterConfig.NodeSelector }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          {{- range $key, $value := $.ClusterConfig.NodeSelector }}
          - key: {{ $key }}
            {{- if ne $value "" }}
            operator: In
            values:
            - {{ $value }}
            {{- else }}
            operator: Exists
            {{- end }}
          {{- end }}
  {{- end }}
  containers:
  - name: test-container
    image: mellanox/rping-test
    command: ["/bin/bash", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        add: ["IPC_LOCK"]
    resources:
      requests:
        nvidia.com/{{$.Sriov.ResourceName}}-{{printf "%c" (add 97 $i)}}: '1'
      limits:
        nvidia.com/{{$.Sriov.ResourceName}}-{{printf "%c" (add 97 $i)}}: '1'
{{if ne $i (sub (len $.ClusterConfig.PFs) 1)}}---{{end -}}
{{- end -}}
{{- end -}}
{{- else}}
apiVersion: v1
kind: Pod
metadata:
  name: sriov-test-pod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: {{.Sriov.NetworkName}}
spec:
  {{- if $.ClusterConfig.NodeSelector }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          {{- range $key, $value := $.ClusterConfig.NodeSelector }}
          - key: {{ $key }}
            {{- if ne $value "" }}
            operator: In
            values:
            - {{ $value }}
            {{- else }}
            operator: Exists
            {{- end }}
          {{- end }}
  {{- end }}
  containers:
  - name: test-container
    image: mellanox/rping-test
    command: ["/bin/bash", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        add: ["IPC_LOCK"]
    resources:
      requests:
        nvidia.com/{{.Sriov.ResourceName}}: '1'
      limits:
        nvidia.com/{{.Sriov.ResourceName}}: '1'
{{- end}}